version: "3"

services:

  php-fpm:
    image: php-fpm
    container_name: vk-hack-laravel
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      CONTAINER_ROLE: app

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: local/Dockerfile
    container_name: vk-hack-nginx
    depends_on:
      - php-fpm
    ports:
      - 8080:443
    volumes:
      - ./:/var/www

  sql:
    image: postgres:latest
    container_name: vk-hack-sql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54321:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: vk-hack-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"

  redis:
    image: redis:latest
    container_name: vk-hack-redis
    ports:
      - 63791:6379

volumes:
  elastic:
    driver: local
  mysql:
    driver: local
